# Generated by Django 4.0.2 on 2022-02-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=2000)),
                ('firstname', models.CharField(default='None', max_length=2000)),
                ('lastname', models.CharField(default='None', max_length=5000)),
                ('email1', models.CharField(default='None', max_length=5000)),
                ('email2', models.CharField(default='None', max_length=5000)),
                ('status', models.CharField(default=False, max_length=5000)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
    ]
