# Generated by Django 4.0.2 on 2022-03-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='All',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=2000)),
                ('firstname', models.CharField(default='None', max_length=2000)),
                ('lastname', models.CharField(default='None', max_length=5000)),
                ('email', models.CharField(default='None', max_length=5000)),
                ('country', models.CharField(default='India', max_length=500)),
                ('history', models.CharField(default='', max_length=50000)),
                ('age', models.IntegerField(default=18)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=2000)),
                ('ISBN', models.CharField(default='None', max_length=2000)),
                ('like', models.CharField(default='unlike', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=2000)),
                ('usernameaa', models.CharField(default='None', max_length=2000)),
                ('ISBN', models.CharField(default='None', max_length=2000)),
                ('like', models.CharField(default='unlike', max_length=2000)),
            ],
        ),
    ]
