# Generated by Django 4.0.2 on 2022-03-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Liked',
        ),
    ]
