# Generated by Django 4.0.2 on 2022-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='country',
            field=models.CharField(default='None', max_length=500),
        ),
    ]
