# Generated by Django 4.0.2 on 2022-02-26 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_all_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all',
            old_name='email1',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='all',
            name='email2',
        ),
        migrations.RemoveField(
            model_name='all',
            name='status',
        ),
    ]
