# Generated by Django 4.0.2 on 2022-02-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_email1_all_email_remove_all_email2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='all',
            name='history',
            field=models.CharField(default='None', max_length=50000),
        ),
    ]
