# Generated by Django 4.0.2 on 2022-02-28 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_all_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='history',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
