# Generated by Django 4.0.2 on 2022-02-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='BookAuthor',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='BookTitle',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='books',
            name='ISBN',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='books',
            name='ImageURLL',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='ImageURLM',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='ImageURLS',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='Publisher',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='books',
            name='YearOfPublication',
            field=models.CharField(max_length=5000),
        ),
    ]
