# Generated by Django 4.0.2 on 2022-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_all_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='None', max_length=2000)),
                ('ISBN', models.CharField(default='None', max_length=2000)),
                ('like', models.CharField(default='unlike', max_length=2000)),
            ],
        ),
        migrations.RemoveField(
            model_name='all',
            name='likes',
        ),
    ]
