# Generated by Django 4.0.2 on 2022-03-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_like_remove_all_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='all',
            name='country',
            field=models.CharField(default='India', max_length=500),
        ),
    ]
